name: Continuous Delivery

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Cloud Provider
      run: |
        gcloud builds submit --tag gcr.io/driven-presence-400200/fastapi-app
        gcloud run deploy fastapi-service --image gcr.io/driven-presence-400200/fastapi-app --platform managed --region us-central1 --allow-unauthenticated
 
